### ISSUE TITLE
Blocked scope declarations not yet supported

### ISSUE THREAD

**Issue by beatfreaker** [bmorelli25/node-async-weather#7]
Getting following error while running `npm start -- -l Pune`

```
/home/ubuntu/workspace/node-async-weather/app.js:2
let weather = require('./weather.js');
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

seems `'use strict';` needs to be added in `.js` files

can i submit PR for the same?

**Comment by bmorelli25** [comment]
Ahhh, I see. Yes, please do

**Comment by beatfreaker** [comment]
PR [#9](https://github.com/bmorelli25/node-async-weather/pull/9) resolves this issue.
